---

### terminate AWS EC/2 instances
- hosts: localhost
  connection: local
  gather_facts: false
  user: root
  pre_tasks:
    - include_vars: variables.yml
  tasks:
    - name: Get EC2 instance IDs
      run_once: true
      ec2_instance_info:
        filters:
          "tag:Type": "{{ ec2_tag_Type }}"
          "tag:Role": "{{ ec2_tag_Role }}"
        region: "{{ ec2_region }}"
      register: instances
    - name: Display instances
      run_once: true
      debug:
        var: instances
