- name: Trigger Build
  hosts: localhost
  vars:
    Uname: "{{ lookup('env', 'JENKINS_USER') }}"
    Pass: "{{ lookup('env', 'JENKINS_PASS') }}"
    TokenName: "{{ lookup('env', 'JENKINS_API_TOKEN') }}"
  tasks:
  - name: Queue build
    uri:
      url: "http://{{ HostName }}:8080/job/{{ JobName }}/build?token={{ TokenName }}"
      method: HEAD
      url_username: "{{ Uname }}"
      url_password: "{{ Pass }}"
      force_basic_auth: yes
      status_code: 201
  - name: Check for build artifact
    command: "curl --silent http://{{ HostName }}/job/{{ JobName }}/{{ BuildNumber }}/artifact/target/{{ ArtifactName }}"
    register: result
    until: result.stdout.find("200 OK") != -1
    retries: 10
    delay: 30
    changed_when: false
