- name: trigger
  hosts: localhost
  vars:
    TokenName: "{{ lookup('env', 'JENKINS_API_TOKEN') }}"
    UserName: "{{ lookup('env', 'JENKINS_USER') }}"
    Password: "{{ lookup('env', 'JENKINS_PASS') }}"
  tasks:
  - name: Queue build
    uri:
      url: http://{{ UserName}}:{{ Password }}@{{ HostName }}:8080/job/{{ JobName }}/build?token={{ TokenName }}
      method: POST
      force_basic_auth: yes
      status_code: 201
