- name: trigger
  hosts: localhost
  vars:
    Uname: "{{ lookup('env', 'JENKINS_USER') }}"
    Pass: "{{ lookup('env', 'JENKINS_PASS') }}"
    TokenName: "{{ lookup('env', 'JENKINS_ANSIBLE_TOKEN') }}"
  tasks:
  - name: Queue build
    uri:
      url: "http://{{ HostName }}:8080/job/{{ JobName }}/build?token={{ TokenName }}"
      method: POST
      user: "{{ Uname }}"
      password: "{{ Pass }}"
      force_basic_auth: yes
      status_code: 201
