- name: trigger
  hosts: localhost
  vars:
    TokenName: "{{ lookup('env', 'JENKINS_API_TOKEN') }}"
  tasks:
  - name: Queue build
    uri:
      url: http://{{ HostName }}:8080/job/{{ JobName }}/build?token=11d479943da58b30913faf0dcb171d8432
      url_username: "{{ lookup('env', 'JENKINS_USER') }}"
      url_password: "{{ lookup('env', 'JENKINS_PASS') }}"
      method: POST
      force_basic_auth: yes
      status_code: 201
