- name: trigger
  hosts: localhost
  vars:
    TokenName: "{{ lookup('env', 'JENKINS_API_TOKEN') }}"
  tasks:
  - name: Queue build
    uri:
      url: http://{{ HostName }}:8080/job/{{ JobName }}/build?token={{ TokenName }}
      user: "{{ lookup('env', 'JENKINS_USER') }}"
      password: "{{ lookup('env', 'JENKINS_PASS') }}"
      method: GET
      force_basic_auth: yes
      status_code: 201
