---
- hosts: all
  become: true
  connection: ssh
  remote_user: ubuntu
  vars:
    Uname: "{{ lookup('env', 'JENKINS_USER') }}"
    Pass: "{{ lookup('env', 'JENKINS_PASS') }}"
    TokenName: "{{ lookup('env', 'JENKINS_API_TOKEN') }}"
  tasks:
    - name: Install web container dependencies
      apt:
        name: tomcat9
        update_cache: yes
        state: build-dep
    - name: Download latest WAR delivery
      uri:
        url: http://{{ HostName }}:8080/job/{{ JobName }}/lastSuccessfulBuild/artifact/{{ ArtifactPath }}
        dest: /tmp
        url_username: "{{ Uname }}"
        url_password: "{{ Pass }}"
        force_basic_auth: yes
        status_code: 200
      
