---
- hosts: all
  become: true
  connection: ssh
  remote_user: ubuntu
  tasks:
    - name: Install web container dependencies
      apt:
        name: tomcat9
        update_cache: yes
    - name: Download latest WAR delivery
      uri:
        url: http://{{ HostName }}:8080/job/{{ JobName }}/lastSuccessfulBuild/artifact/{{ ArtifactPath }}
        dest: /tmp
      
