---
- hosts: all
  become: true
  connection: ssh
  remote_user: ubuntu
  vars:
    Uname: "{{ lookup('env', 'JENKINS_USER') }}"
    Pass: "{{ lookup('env', 'JENKINS_PASS') }}"
    TokenName: "{{ lookup('env', 'JENKINS_API_TOKEN') }}"
    TomcatServer: "tomcat9"
    DeploymentPath: "/var/lib/{{ TomcatServer }}/webapps"
  tasks:
    - name: Install web container dependencies
      apt:
        name: "{{ TomcatServer }}"
        update_cache: yes
        state: present
    - name: Clean previous deployment
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ DeploymentPath }}/ROOT.war"
        - "{{ DeploymentPath }}/ROOT"
    - name: Download latest WAR delivery
      uri:
        url: "http://{{ HostName }}:8080/job/{{ JobName }}/lastSuccessfulBuild/artifact/{{ ArtifactPath }}"
        dest: "{{ DeploymentPath }}/ROOT.war"
        url_username: "{{ Uname }}"
        url_password: "{{ Pass }}"
        force_basic_auth: yes
        status_code: 200
        notify:
        - restart "{{ TomcatServer }}"
  handlers:
    - name: Restart "{{ TomcatServer }}"
      service:
        name: "{{ TomcatServer }}"
        state: restarted
